Repository fga-eps-mds/2023-2-GEROcuidado-Doc, pull requests merged in 2023-10, with the labels that each got.

#60 Reunião Geral 03/10
  docs/reunioes/Semana_5/reuniao_Geral_03_10.md
  mkdocs.yml
Labels: documentation, meeting

#61 Adiciona reuniao com o PO dia 04/10
  docs/reunioes/Semana_5/reuniao_PO_04_10.md
  mkdocs.yml
Labels: documentation, cliente GEROcuidado, meeting

#81 [#71] Documentação das ferramentas
  docs/assets/imagens/Docker_logo-700x588.png
  docs/assets/imagens/React.png
  docs/assets/imagens/logo-wordmark-light.png
  docs/assets/imagens/logo-wordmark.png:Zone.Identifier
  docs/assets/imagens/nestjs-272666.png
  docs/assets/imagens/postgresql-512.png
  docs/planejamento/ferramentas.md
  mkdocs.yml
Labels: documentation, EPS, MDS, R1

#103 Template de história de usuário
  .github/ISSUE_TEMPLATE/template-de-historia-de-usuario.md
Labels: documentation, US

#118 [#80] Atualiza documento de gerenciamento de risco
  docs/assets/imagens/EAR.png
  docs/planejamento/gerenciamento_de_riscos.md
Labels: documentation, enhancement, increment

#105 [IN PROGRESS] Documento do EAP
  docs/planejamento/eap.md
  mkdocs.yml
Labels: documentation, in-progress, EPS, R1

#117 Adiciona o documento de arquitetura
  docs/assets/imagens/Arquitetura.png
  docs/produto/documento_arquitetura.md
  mkdocs.yml
Labels: in-progress
