Repository fga-eps-mds/2023-2-GEROcuidado-Doc, pull requests merged in 2023-09, with the labels that each got.

#4 Adiciona ata de reuniao do dia 05_09
  reunioes/Semana_1/reuniao_05_09.md
Labels: documentation, EPS, easy, meeting

#8 Plano de contribuição
  .github/ISSUE_TEMPLATE/template-de-bug-report.md
  .github/template-dos-pull-requests.md
  docs/projeto/plano_de_contribuicao.md
  mkdocs.yml
Labels: documentation, EPS

#9 Plano de comunicação
  docs/projeto/plano_de_comunicacao.md
  mkdocs.yml
Labels: documentation, EPS, easy

#11 Adicionando quadro de disponibilidade
  README.md
  docs/assets/gero.png
  docs/planejamento/plano_de_comunicacao.md
  docs/planejamento/plano_de_contribuicao.md
  docs/planejamento/quadro_de_disponibilidade.md
  mkdocs.yml
Labels: documentation, EPS

#17 Documento de metodologias
  docs/planejamento/metodologia.md
  mkdocs.yml
Labels: documentation, EPS, easy

#18 Plano gerenciamento de riscos
  docs/planejamento/gerenciamento_de_riscos.md
  docs/planejamento/metodologia.md
  mkdocs.yml
Labels: documentation, EPS, medium

#24 Corrige a pagina de gerenciamento de risco
  docs/planejamento/gerenciamento_de_riscos.md
  mkdocs.yml
Labels: bug, documentation, easy

#25 Atualiza documentos
  docs/planejamento/plano_de_comunicacao.md
  docs/planejamento/plano_de_contribuicao.md
Labels: documentation, enhancement

#41 (#28) Treinamento Git
  docs/treinamentos/treinamento-git.md
Labels: documentation

#43 (#29) Adiciona treinamento de metodologias ageis
  docs/assets/imagens/kanban.png
  docs/assets/imagens/scrum.png
  docs/assets/imagens/xp.png
  docs/treinamentos/treinamento_git.md
  docs/treinamentos/treinamento_linux.md
  docs/treinamentos/treinamento_metodologias_ageis.md
  mkdocs.yml
Labels: documentation, training

#44 (#16) Adiciona quadro de conhecimento
  docs/assets/imagens/quadro_conhecimento/quadro_conhecimento_semana2.png
  docs/planejamento/quadro_conhecimento.md
  mkdocs.yml
Labels: documentation, easy

#38 ATAs de reuniões
  docs/reunioes/Semana_1/reuniao_EPS_04_09.md
  docs/reunioes/Semana_1/reuniao_Geral_05_09.md
  docs/reunioes/Semana_1/reuniao_PO_06_09.md
  docs/reunioes/Semana_2/reuniao_Geral_12_09.md
  docs/reunioes/Semana_2/reuniao_Lean_Inception_Dia1_17_09.md
  docs/reunioes/Semana_2/reuniao_PO_13_09.md
  docs/reunioes/Semana_3/reuniao_Geral_19_09.md
  docs/reunioes/Semana_3/reuniao_PO_20_09.md
  docs/reunioes/Semana_3/reuniao_Treinamento_e_Lean_Inception_Dia2_23_09.md
  docs/reunioes/Semana_4/reuniao_Geral_26_09.md
  docs/reunioes/Semana_4/reuniao_PO_27_09.md
  docs/reunioes/padrao.md
  mkdocs.yml
Labels: documentation, meeting
